export declare const action: string
export declare const actionIcon: string
export declare const actionMinus: string
export declare const actionPlus: string
export declare const inputWrapper: string
export declare const number: string
export declare const numberInput_color_first: string
export declare const numberInput_color_second: string
export declare const numberInputRoot: string
