export declare const backgroundAppear: string
export declare const contentBlock: string
export declare const logoIcon: string
export declare const sphereImage: string
export declare const sphereImageBottom: string
export declare const sphereImageTop: string
export declare const welcomeBackground: string
export declare const welcomeBackgroundContainer: string
export declare const welcomeButton: string
export declare const welcomeDescription: string
export declare const welcomeRoot: string
